### ISSUE TITLE
导入项目报错

### ISSUE THREAD

**Issue by WhiteCosmos** [RabiAPI/RabiAPI-Support#11]
![image](https://user-images.githubusercontent.com/5286570/100993695-b0a38000-3590-11eb-9844-932ce8f88b4a.png)

**Comment by qiuzhaokun** [comment]
<img width="715" alt="image" src="https://user-images.githubusercontent.com/16495106/100994137-3f180180-3591-11eb-8e4c-1e9ce11ff505.png">

**Comment by WhiteCosmos** [comment]
@qiuzhaokun 在View里面开启控制台看一下有没有报错信息

**Comment by qiuzhaokun** [comment]
<img width="2252" alt="image" src="https://user-images.githubusercontent.com/16495106/100995689-13961680-3593-11eb-991e-937f9acc9fa0.png">
溢出了

**Comment by WhiteCosmos** [comment]
@qiuzhaokun 项目很大吗？还是接口非常多？

**Comment by qiuzhaokun** [comment]
@WhiteCosmos 项目很大，常年积累，以及接口非常多，600多个吧

**Comment by WhiteCosmos** [comment]
@qiuzhaokun 那我下个版本先调大Heap试试

**Comment by WhiteCosmos** [comment]
@qiuzhaokun 1.2.3 版本已发布

**Comment by qiuzhaokun** [comment]
@WhiteCosmos 感谢

**Comment by WhiteCosmos** [comment]
@qiuzhaokun 没有问题的话告知一下 我可以关闭issue 谢谢~
