### ISSUE TITLE
mac 10.15.7 程序坞在右侧时无法正确显示

### ISSUE THREAD

**Issue by ghost** [RabiAPI/RabiAPI-Support#20]
打开软件的时候，软件的宽度会铺满整个屏幕，这样的话程序坞在右侧或者左侧的时候就会有功能按键被遮挡，且软件在调整大小的时候并不能完全自定义大小，所以还是会遮挡一部分软件内容。建议在打开的时候判断程序坞所在位置，并合理展示软件宽度。

**Comment by WhiteCosmos** [comment]
> 打开软件的时候，软件的宽度会铺满整个屏幕，这样的话程序坞在右侧或者左侧的时候就会有功能按键被遮挡，且软件在调整大小的时候并不能完全自定义大小，所以还是会遮挡一部分软件内容。建议在打开的时候判断程序坞所在位置，并合理展示软件宽度。

是13寸屏幕吗？目前限制了最小分辨率是1280 * 800 默认是 1400 * 900

**Comment by ghost** [comment]
> > ：软件的时候，软件的宽度会铺满整个屏幕，这样的话程序坞在右侧或者左边的时候就会有功能按键被遮挡，并且软件在调整大小的时候并不能完全自定义大小，所以还是会遮挡部分软件内容。建议在打开的时候判断程序坞所在位置，并合理展示软件宽度。
> 
> 是13寸屏幕吗？目前限制了最小分辨率是1280 * 800默认是1400 * 900

是的，13.3寸屏幕。

**Comment by WhiteCosmos** [comment]
1.3.5 更新最小为720P分辨率，同时默认分辨率改为1280 * 800
