### ISSUE TITLE
SpringBoot2.x GET请求使用实体类作为入参时无法导出

### ISSUE THREAD

**Issue by shotacon** [RabiAPI/RabiAPI-Support#23]
`@GetMapping("/driver")`
`public ResultMsg selectDriver(DriverInfoQuery driverInfoQuery) {`
`    return ResultMsg.succ();`
`}`

GET请求在实体类作为入参时无法识别

**Comment by WhiteCosmos** [comment]
> `@GetMapping("/driver")`
> `public ResultMsg selectDriver(DriverInfoQuery driverInfoQuery) {`
> ` return ResultMsg.succ();`
> `}`
> 
> GET请求在实体类作为入参时无法识别

这个 DriverInfoQuery 是第三方JAR包依赖进来的还是在同一个项目里的?

**Comment by shotacon** [comment]
> > `@GetMapping("/driver")`
> > `public ResultMsg selectDriver(DriverInfoQuery driverInfoQuery) {`
> > ` return ResultMsg.succ();`
> > `}`
> > GET请求在实体类作为入参时无法识别
> 
> 这个 DriverInfoQuery 是第三方JAR包依赖进来的还是在同一个项目里的?

自定义的一个接收参数的类. 现在GET请求可以用实体类来接收参数啊.

**Comment by WhiteCosmos** [comment]
1.3.5 更新 Get请求使用实体类，其中的字段为会解析为Query或Path参数(如果在字段出现在Path中)
